---
- name: OpenShift Metrics
  hosts: oo_first_master
  roles:
  - role: openshift_metrics
    when: openshift_metrics_install_metrics | default(false) | bool


- name: OpenShift Metrics
  hosts: oo_masters:!oo_first_master
  serial: 1
  tasks:
  - name: Setup the non-first masters configs
    include_role:
      name: openshift_metrics
      tasks_from: update_master_config.yaml
    when: openshift_metrics_install_metrics | default(false) | bool
