---
- name: Service Catalog
  hosts: oo_first_master
  roles:
  - openshift_service_catalog
  - ansible_service_broker
  - template_service_broker
  vars:
    first_master: "{{ groups.oo_first_master[0] }}"
