---
# Create the required PVs for the App and the DB
- name: Note the App PV Size from Template Parameters
  set_fact:
    openshift_cfme_app_pv_size: "{{ openshift_cfme_template_parameters.APPLICATION_VOLUME_CAPACITY }}"
  when:
    - openshift_cfme_template_parameters.APPLICATION_VOLUME_CAPACITY is defined

- name: Note the App PV Size from defaults
  set_fact:
    openshift_cfme_app_pv_size: "{{ __openshift_cfme_app_pv_size }}"
  when:
    - openshift_cfme_template_parameters.APPLICATION_VOLUME_CAPACITY is not defined

- when: openshift_cfme_app_template in ['miq-template', 'cfme-template']
  block:
    - name: Note the DB PV Size from Template Parameters
      set_fact:
        openshift_cfme_db_pv_size: "{{ openshift_cfme_template_parameters.DATABASE_VOLUME_CAPACITY }}"
      when:
        - openshift_cfme_template_parameters.DATABASE_VOLUME_CAPACITY is defined

    - name: Note the DB PV Size from defaults
      set_fact:
        openshift_cfme_db_pv_size: "{{ __openshift_cfme_db_pv_size }}"
      when:
        - openshift_cfme_template_parameters.DATABASE_VOLUME_CAPACITY is not defined

- name: Check if the CFME App PV has been created
  oc_obj:
    namespace: "{{ openshift_cfme_project }}"
    state: list
    kind: pv
    name: "{{ openshift_cfme_flavor_short }}-app"
  register: miq_app_pv_check

- name: Check if the CFME DB PV has been created
  oc_obj:
    namespace: "{{ openshift_cfme_project }}"
    state: list
    kind: pv
    name: "{{ openshift_cfme_flavor_short }}-db"
  register: miq_db_pv_check
  when:
    - openshift_cfme_app_template in ['miq-template', 'cfme-template']

- name: Ensure the CFME App PV is created
  oc_process:
    namespace: "{{ openshift_cfme_project }}"
    template_name: "{{ openshift_cfme_flavor }}-app-pv"
    create: True
    params:
      PV_SIZE: "{{ openshift_cfme_app_pv_size }}"
      BASE_PATH: "{{ openshift_cfme_storage_nfs_base_dir }}"
      NFS_HOST: "{{ openshift_cfme_nfs_server }}"
  when: miq_app_pv_check.results.results == [{}]

- name: Ensure the CFME DB PV is created
  oc_process:
    namespace: "{{ openshift_cfme_project }}"
    template_name: "{{ openshift_cfme_flavor }}-db-pv"
    create: True
    params:
      PV_SIZE: "{{ openshift_cfme_db_pv_size }}"
      BASE_PATH: "{{ openshift_cfme_storage_nfs_base_dir }}"
      NFS_HOST: "{{ openshift_cfme_nfs_server }}"
  when:
    - openshift_cfme_app_template in ['miq-template', 'cfme-template']
    - miq_db_pv_check.results.results == [{}]
