---
- command: mktemp -d /tmp/tsb-ansible-XXXXXX
  register: mktemp
  changed_when: False
  become: no

- copy:
    src: "{{ __tsb_files_location }}/{{ item }}"
    dest: "{{ mktemp.stdout }}/{{ __tsb_template_file }}"

- name: Delete TSB objects
  shell: >
    oc process -f "{{ __tsb_files_location }}/{{ __tsb_template_file }}" | kubectl delete -f -

- name: empty out tech preview extension file for service console UI
  copy:
    src: remove-openshift-ansible-catalog-console.js
    dest: /etc/origin/master/openshift-ansible-catalog-console.js

- oc_project:
    name: openshift-template-service-broker
    state: absent

- file:
    state: absent
    name: "{{ mktemp.stdout }}"
  changed_when: False
  become: no
